------------------------------------------------------------
-- 1) MEMBER
------------------------------------------------------------
CREATE TABLE MEMBER (
    MEM_ID              NUMBER(12) CONSTRAINT PK_MEMBER PRIMARY KEY,
    MEM_PASS          VARCHAR2(100 CHAR)    NOT NULL,   
    MEM_NAME         VARCHAR2(50 CHAR)     NOT NULL,   
    MEM_ZIP             VARCHAR2(5 CHAR)       NOT NULL,   
    MEM_ADD1          VARCHAR2(200 CHAR)   NOT NULL,   
    MEM_ADD2          VARCHAR2(200 CHAR)   NOT NULL,   
    MEM_PHONE        VARCHAR2(20 BYTE)      NOT NULL,   
    MEM_EMAIL         VARCHAR2(254 BYTE)     NOT NULL,   
    GAME_NICKNAME  VARCHAR2(30 CHAR)     NOT NULL,   
    CREATED_DATE      DATE DEFAULT SYSDATE NOT NULL,  
    DELETED_DATE      DATE,                           
    DELETED_REASON  VARCHAR2(255 CHAR),             
    STATUS         VARCHAR2(10 CHAR) DEFAULT 'ACTIVE' NOT NULL
                   CONSTRAINT CK_MEMBER_STATUS CHECK
                      (STATUS IN ('ACTIVE','SUSPENDED','DELETED','PENDING','BANNED')),
    ROLE           VARCHAR2(10 CHAR) DEFAULT 'USER' NOT NULL
                   CONSTRAINT CK_MEMBER_ROLE CHECK
                      (ROLE IN ('USER','ADMIN')),
    CONSTRAINT UQ_MEMBER_EMAIL UNIQUE (MEM_EMAIL),
    CONSTRAINT UQ_MEMBER_NICK  UNIQUE (GAME_NICKNAME)
);

COMMENT ON TABLE MEMBER IS '회원 기본 정보(사용자/관리자 통합, ROLE로 구분)';
COMMENT ON COLUMN MEMBER.MEM_ID         IS '회원 PK';
COMMENT ON COLUMN MEMBER.MEM_PASS       IS '비밀번호 해시';
COMMENT ON COLUMN MEMBER.MEM_NAME       IS '회원 이름(실명)';
COMMENT ON COLUMN MEMBER.MEM_ZIP        IS '우편번호(5자리)';
COMMENT ON COLUMN MEMBER.MEM_ADD1       IS '기본 주소';
COMMENT ON COLUMN MEMBER.MEM_ADD2       IS '상세 주소';
COMMENT ON COLUMN MEMBER.MEM_PHONE      IS '핸드폰번호';
COMMENT ON COLUMN MEMBER.MEM_EMAIL      IS '로그인 및 알림용 이메일(고유)';
COMMENT ON COLUMN MEMBER.GAME_NICKNAME  IS '게임 내 표시 닉네임(고유)';
COMMENT ON COLUMN MEMBER.CREATED_DATE   IS '계정 생성일';
COMMENT ON COLUMN MEMBER.DELETED_DATE   IS '삭제/탈퇴 처리일';
COMMENT ON COLUMN MEMBER.DELETED_REASON IS '삭제/탈퇴 사유';
COMMENT ON COLUMN MEMBER.STATUS         IS '계정 상태(ENUM)';
COMMENT ON COLUMN MEMBER.ROLE           IS '권한(ADMIN/USER)';

-- MEMBER 시퀀스
CREATE SEQUENCE SEQ_MEMBER_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- MEMBER 테이블 MEM_ID 컬럼의 다음 시퀀스 조회   
-- SELECT SEQ_MEMBER_ID.NEXTVAL FROM DUAL;
------------------------------------------------------------
-- 2) BOARD (리뷰 게시판)
------------------------------------------------------------
CREATE TABLE BOARD (
    BOARD_ID     NUMBER(12) CONSTRAINT PK_BOARD PRIMARY KEY,
    MEM_ID        NUMBER(12)              NOT NULL,
    TITLE            VARCHAR2(200 CHAR) NOT NULL,
    CONTENT     CLOB                        NOT NULL,
    CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_DATE DATE,
    VIEW_COUNT   NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY (MEM_ID)
        REFERENCES MEMBER (MEM_ID)
);

COMMENT ON TABLE BOARD IS '리뷰 게시판(회원 작성 글)';
COMMENT ON COLUMN BOARD.BOARD_ID     IS '게시글 PK';
COMMENT ON COLUMN BOARD.MEM_ID       IS '작성자 MEMBER.FK';
COMMENT ON COLUMN BOARD.TITLE        IS '제목(200자)';
COMMENT ON COLUMN BOARD.CONTENT      IS '내용(CLOB)';
COMMENT ON COLUMN BOARD.CREATED_DATE IS '작성일';
COMMENT ON COLUMN BOARD.UPDATED_DATE IS '수정일';
COMMENT ON COLUMN BOARD.VIEW_COUNT   IS '조회수(기본 0)';

-- BOARD 시퀀스
CREATE SEQUENCE SEQ_BOARD_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- BOARD 테이블 BOARD_ID 컬럼의 다음 시퀀스 조회       
-- SELECT SEQ_BOARD_ID.NEXTVAL FROM DUAL;
------------------------------------------------------------
-- 3) NOTICE (공지사항)
------------------------------------------------------------
CREATE TABLE NOTICE (
    NOTICE_ID    NUMBER(12) CONSTRAINT PK_NOTICE PRIMARY KEY,
    ADMIN_ID    NUMBER(12)                   NOT NULL,
    TITLE           VARCHAR2(200 CHAR)      NOT NULL,
    CONTENT    CLOB                              NOT NULL,
    CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_DATE DATE,
    VIEW_COUNT   NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_NOTICE_ADMIN FOREIGN KEY (ADMIN_ID)
        REFERENCES MEMBER (MEM_ID)
);

COMMENT ON TABLE NOTICE IS '공지사항(관리자 공지)';
COMMENT ON COLUMN NOTICE.NOTICE_ID    IS '공지 PK';
COMMENT ON COLUMN NOTICE.ADMIN_ID     IS '작성 관리자 MEMBER.FK(ROLE=ADMIN은 JS에서 검증)';
COMMENT ON COLUMN NOTICE.TITLE        IS '제목(200자)';
COMMENT ON COLUMN NOTICE.CONTENT      IS '내용(CLOB)';
COMMENT ON COLUMN NOTICE.CREATED_DATE IS '작성일';
COMMENT ON COLUMN NOTICE.UPDATED_DATE IS '수정일(앱에서 갱신)';
COMMENT ON COLUMN NOTICE.VIEW_COUNT   IS '조회수(기본 0)';

-- NOTICE 시퀀스
CREATE SEQUENCE SEQ_NOTICE_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- NOTICE 테이블 NOTICE_ID 컬럼의 다음 시퀀스 조회   
-- SELECT SEQ_NOTICE_ID.NEXTVAL FROM DUAL;
------------------------------------------------------------
-- 4) FILE (자료실)
------------------------------------------------------------
CREATE TABLE FILES (
    FILE_ID        NUMBER(12) CONSTRAINT PK_FILE PRIMARY KEY,
    MEM_ID                  NUMBER(12)                    NOT NULL,
    FILE_NAME              VARCHAR2(255 BYTE)         NOT NULL,  
    FILE_URL                 VARCHAR2(1024 BYTE)       NOT NULL,  
    CREATED_DATE         DATE DEFAULT SYSDATE    NOT NULL,
    DOWNLOAD_COUNT NUMBER(10) DEFAULT 0     NOT NULL,
    CONSTRAINT FK_FILE_MEMBER FOREIGN KEY (MEM_ID)
        REFERENCES MEMBER (MEM_ID)
);

COMMENT ON TABLE FILES IS '자료실 파일 메타데이터';
COMMENT ON COLUMN FILES.FILE_ID        IS '파일 PK';
COMMENT ON COLUMN FILES.MEM_ID         IS '업로더 MEMBER.FK';
COMMENT ON COLUMN FILES.FILE_NAME      IS '원본 파일명(255자)';
COMMENT ON COLUMN FILES.FILE_URL       IS '저장 경로/URL(최대 1024자)';
COMMENT ON COLUMN FILES.CREATED_DATE   IS '업로드일';
COMMENT ON COLUMN FILES.DOWNLOAD_COUNT IS '다운로드 수(기본 0)';

-- FILES 시퀀스
CREATE SEQUENCE SEQ_FILES_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- FILES 테이블 FILES_ID 컬럼의 다음 시퀀스 조회    
-- SELECT SEQ_FILES_ID.NEXTVAL FROM DUAL;
 
 COMMIT;   